### ISSUE TITLE
日本語参考文献の掲載誌が太字になる

### ISSUE THREAD

**Issue by chess0000** [being24/latex-template-ja#64]
bibの日本語対応のためmain.texやclasses/report.clsで`junsrt`を追記したり`.latexmkrc`で`$bibtex = pbibtex`にしたりしましたが、掲載誌の太字化現象が改善されませんでした。(`\bibliographystyle{junsrt}`はそもそもビルドエラー)

bibの日本語対応はどのようにしたらよいでしょうか。

**Comment by being24** [comment]
解決しました

clsファイルの
`\usepackage[backend=biber,style=ieee]{biblatex} % biblatexを使用するためのパッケージ
\addbibresource{references.bib}`

これを

`\usepackage[backend=biber,style=trad-unsrt]{biblatex} % biblatexを使用するためのパッケージ
\addbibresource{references.bib}
\DeclareFieldFormat{journaltitle}{\textit{#1}}`

これに変更してみてください

**Comment by chess0000** [comment]
解決しました。
ありがとうございます！
